name: app_gs3
description: "App bancario GS3"

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

# Ambiente do SDK do Flutter
environment:
  sdk: ^3.6.1

# Dependências do projeto
dependencies:
  flutter:
    sdk: flutter

  #Dependencias
  mobx: ^2.5.0 # MobX Pacote de gerenciamento de estado baseado em reações

  flutter_mobx: ^2.3.0 # Integração do MobX com o Flutter

  cupertino_icons: ^1.0.8

  path_provider: ^2.0.14 # Facilita o acesso ao sistema de arquivos para leitura e escrita

  provider: ^6.0.5 # Gerenciamento de estado fácil com suporte para ChangeNotifier

# Dependências de desenvolvimento (dev_dependencies)
dev_dependencies:
  # Pacote para escrever e executar testes no Flutter
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^5.0.0 # Conjunto de regras de linting recomendadas para projetos Flutter

  mobx_codegen: ^2.2.0 # Gerador de código para facilitar o uso do MobX

  build_runner: ^2.3.3 # Ferramenta que executa geradores de código durante o tempo de compilação

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # Habilita o uso do Material Design no aplicativo
  uses-material-design: true

  # Lista de ativos (imagens) que serão incluídos no aplicativo
  assets:
    - images/


  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #

